version: '2'
services:
  db:
    image: arungupta/couchbase-node
    ports:
      - 8091-8093:8091-8093
      - 9100-9105:9100-9105
      - 11207:11207
      - 11209-11211:11209-11211
      - 18091-18093:18091-18093
      - 4369:4369
      - 21100-21299:21100-21299

networks:
  default:
    driver: overlay
